---
name: googletest
version: 1.17.0
source: https://github.com/google/googletest/archive/refs/tags/v1.17.0.tar.gz
description: |
  C++ Testing and Mocking Framework.
brief_description: C++ Testing and Mocking Framework.
category: testing
cmake:
  CMAKE_BUILD_TYPE: Release
  BUILD_SHARED_LIBS: ON
  CMAKE_POSITION_INDEPENDENT_CODE: ON
  CMAKE_INSTALL_RPATH_USE_LINK_PATH: ON
