---
name: google-benchmark
version: 1.9.4
source: https://github.com/google/benchmark/archive/refs/tags/v1.9.4.tar.gz
description: |
  Benchmarking framework for C++.
brief_description: Benchmarking framework for C++.
category: benchmarking
cmake:
  CMAKE_BUILD_TYPE: Release
  CMAKE_POSITION_INDEPENDENT_CODE: ON
  BENCHMARK_ENABLE_TESTING: OFF
  CMAKE_INSTALL_RPATH_USE_LINK_PATH: ON
