---
name: kokkos
version: 4.7.02
source: https://github.com/kokkos/kokkos/archive/refs/tags/4.7.02.tar.gz
description: |
  Kokkos is a portable, open-source C++ library for high-performance parallel programming.
  Kokkos is designed to be portable across many architectures and compilers.
brief_description: Portable C++ library for high-performance parallel programming.
category: parallelism, portable, GPU.
cmake:
  CMAKE_BUILD_TYPE: Release
  Kokkos_ARCH_NATIVE: ON
  Kokkos_ENABLE_CUDA: ON
  # Kokkos_ENABLE_HIP: ON
  # Kokkos_ENABLE_OPENMP: ON
