---
name: kokkos
version: 5.1.1
source: https://github.com/kokkos/kokkos/archive/refs/tags/5.1.1.tar.gz
description: |
  Kokkos is a portable, open-source C++ library for high-performance parallel programming.
  Kokkos is designed to be portable across many architectures and compilers.
brief_description: Portable C++ library for high-performance parallel programming.
category: parallelism, portable, GPU.
cmake:
  CMAKE_BUILD_TYPE: Release
  BUILD_SHARED_LIBS: ON
  CMAKE_POSITION_INDEPENDENT_CODE: ON
  CMAKE_INSTALL_RPATH_USE_LINK_PATH: ON

  # For CUDA
  Kokkos_ARCH_NATIVE: ON
  Kokkos_ENABLE_CUDA: ON

  # For HIP
#  Kokkos_ENABLE_HIP: ON
#  DCMAKE_CXX_COMPILER: amdclang++

