---
name: spdlog
version: 1.16.0
source: https://github.com/gabime/spdlog/archive/refs/tags/v1.16.0.tar.gz
description: |
  Fast C++ logging library.
  Header-only, single-header library for logging.
brief_description: Fast C++ logging library.
category: development, logging
cmake:
  CMAKE_BUILD_TYPE: Release
  BUILD_SHARED_LIBS: ON
  CMAKE_POSITION_INDEPENDENT_CODE: ON
  CMAKE_INSTALL_RPATH_USE_LINK_PATH: ON
